prefix		?= /usr/local
exec_prefix	?= $(prefix)
bindir		?= $(exec_prefix)/bin
sbindir		?= $(exec_prefix)/sbin
libexecdir	?= $(exec_prefix)/libexec
datarootdir	?= $(prefix)/share
datadir		?= $(prefix)/bin
sysconfdir	?= $(prefix)/etc
sharedstatedir	?= $(prefix)/com
localstatedir	?= $(prefix)/var
runstatedir	?= $(localstatedir)/run
includedir	?= $(prefix)/include
oldincludedir	?= /usr/include
docdir		?= $(datarootdir)/doc
infodir		?= $(docdir)
htmldir		?= $(docdir)
dvidir		?= $(docdir)
pdfdir		?= $(docdir)
psdir		?= $(docdir)
libdir		?= $(exec_prefix)/lib
lispdir		?= $(datarootdir)/emacs/site-lisp
localedir	?= $(datarootdir)/locale
mandir		?= $(datarootdir)/man

debug::
	@echo ">>> $(SELFDIR).$@:"
	@echo "  - MAKEFILE_LIST=$(MAKEFILE_LIST)"
	@echo "  - prefix=$(prefix)"
	@echo "  - exec_prefix=$(exec_prefix)"
	@echo "  - bindir=$(bindir)"
	@echo "  - sbindir=$(sbindir)"
	@echo "  - libexecdir=$(libexecdir)"
	@echo "  - datarootdir=$(datarootdir)"
	@echo "  - datadir=$(datadir)"
	@echo "  - sysconfdir=$(sysconfdir)"
	@echo "  - sharedstatedir=$(sharedstatedir)"
	@echo "  - localstatedir=$(localstatedir)"
	@echo "  - runstatedir=$(runstatedir)"
	@echo "  - includedir=$(includedir)"
	@echo "  - oldincludedir=$(oldincludedir)"
	@echo "  - docdir=$(docdir)"
	@echo "  - infodir=$(infodir)"
	@echo "  - htmldir=$(htmldir)"
	@echo "  - dvidir=$(dvidir)"
	@echo "  - pdfdir=$(pdfdir)"
	@echo "  - psdir=$(psdir)"
	@echo "  - libdir=$(libdir)"
	@echo "  - lispdir=$(lispdir)"
	@echo "  - localedir=$(localedir)"
	@echo "  - mandir=$(mandir)"
	@echo "<<< $(SELFDIR).$@"
