#!/bin/sh -e

VERSION=0.1
export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export ETHMAC=$(cat /etc/security/ethmac 2>/dev/null || echo "F8:81:1A:00:00:00")

die() {
	echo "Error: $*" >&2
	exit 1
}

usage() {
	cat <<EOF
Usage: ${0##*/} [OPTIONS] [RUNLEVEL]

Options:
 -b or emergency        Single user mode boot.
 -s or -S or single     Boot directly into a single user shell without running
                        and other startup scripts.
 -D or --debug          Turn on debug mode.
 -q or --quiet          Turn off verbosity.
 -v or --verbose        Turn on verbosity.
 -h or --help           Display this message.
 -V or --version        Display the version.
EOF
}

. /etc/init.d/mount-linuxfs
. /etc/init.d/mdev
. /etc/init.d/mount-tmp
. /etc/init.d/console
. /etc/init.d/oops

while [ $# -ne 0 ]; do
	if [ "$1" = -h ] || [ "$1" = --help ]; then
		usage
		exit 0
	elif [ "$1" = "-V" ] || [ "$1" = "--version" ] ; then
		echo $VERSION
		exit 0
	elif [ "$1" = -D ] || [ "$1" = debug ]; then
		export DEBUG=1
	elif [ "$1" = -v ] || [ "$1" = verbose ]; then
		export VERBOSE=1
	elif [ "$1" = -q ] || [ "$1" = quiet ]; then
		export QUIET=1
	elif echo "$1" | grep -qE "^[a-zA-Z0-9_]+="; then
		var=$(echo $1 | cut -d= -f1)
		val=$(echo $1 | cut -d= -f2)
		export $var=$val
	elif [ "$1" = -b ] || [ "$1" = emergency ]; then
		mode=emergency
	elif [ "$1" = -s ] || [ "$1" = single ]; then
		mode=single
	elif [ -z "$runlevel" ]; then
		if echo "$1" | grep -E "^[0-6]$"; then
			runlevel=$1
		elif echo "$1" | grep -E "^[Ss]$"; then
			mode=single
			runlevel=$1
		else
			die "Unknown run-level $1!"
		fi
	else
		usage
		die "Too many arguments!"
	fi
	shift
done
runlevel=${runlevel:-5}

case $mode in
emergency) exec /bin/sh;;
single)    exec /sbin/sulogin;;
*)         [ -x /etc/rc.local ] && exec /etc/rc.local $runlevel;;
esac

echo "Oops... ${0##*/} is about to exit!" >&2
exit 1
