#!/bin/sh

#if [ -e /dev/ttyS0 ]; then
#	exec >/dev/ttyS0 2>/dev/ttyS0
#fi

echo "before exec" >>/dev/ttyAT0
ls -l /proc/$$/fd >>/dev/ttyAT0

if [ -e /dev/tty ] && [ tty=$(cttyhack) ] && echo tty=$tty && [ -n "$tty" ]; then
	export LOGIN="/sbin/getty $tty 115200"
	exec >$tty 2>&1 <$tty
fi >>/dev/ttyAT0 2>&1
cttyhack >>/dev/ttyAT0 || true

echo "after exec" >>/dev/ttyAT0
ls -l /proc/$$/fd >>/dev/ttyAT0
