#!/bin/sh

# Execute a login on exit and respawn
oops() {
	[ $? -eq 0 -a $$ -ne 1 ] && return

	login=$LOGIN
	if [ -z "$login" ]; then
		tty=$(cttyhack | sed -e 's,^/dev/,,')
		if [ -n "$tty" -a "$tty" != tty ]; then
			login="/sbin/getty $tty 115200"
		else
			login="/bin/login -p"
		fi
	fi

	while true; do
		$login || err=$?
		echo "${login%% *}: exited with ${err:-0}! respawning..." >&2
		unset err
		sleep 1
	done
}
trap oops 0
