#!/bin/sh

# Execute a login on exit and respawn
oops() {
	[ $? -eq 0 -a $$ -ne 1 ] && return

set -x
	login=$LOGIN
echo "login=$login" >>/dev/ttyAT0
	if [ -z "$login" ]; then
		tty=$(cttyhack | sed -e 's,^/dev/,,')
echo "tty=$tty" >>/dev/ttyAT0
		if [ -n "$tty" -a "$tty" != tty ]; then
			login="/sbin/getty $tty 115200"
		else
			login="/bin/login -p"
		fi
	fi
echo "login=$login" >>/dev/ttyAT0

	while true; do
		$login || err=$?
		echo "${login%% *}: exited with ${err:-0}! respawning..." >&2
		unset err
		sleep 1
	done
}
trap oops 0
