#!/bin/sh

VERSION=0.2

die() {
	echo "Error: $*" >&2
	exit 1
}

usage() {
	cat <<EOF
Usage: ${0##*/} [OPTIONS]

Options:
 persistentdir=DIR      Set persistent mount point [default: /media/persistent]
 persistentopts=OPTS    Set persistent mount options [ex: -osync].
 chrootdir=DIR          Set chroot directory [default: /media/chroot].
 chrootopts=OPTS        Setplay this message.
EOF
}

. /etc/init.d/mount-linuxfs
. /etc/init.d/mdev
. /etc/init.d/console
. /etc/init.d/oops

PERSISTENTDIR=/media/persistent
CHROOTDIR=/media/chroot
while [ $# -ne 0 ]; do
	if echo "$1" | grep -qE "^ramfs\.[a-zA-Z0-9_]+="; then
		v=$(echo $1 | cut -d. -f2)
		var=$(echo $v | cut -d= -f1 | sed -e 's,.,\U&,g')
		val=$(echo $v | cut -d= -f2)
		export $var=$val
	else
		initargs="$initargs $1"
	fi
	shift
done

echo "Mounting persistent directory to $PERSISTENTDIR..."
MOUNTDIR=$PERSISTENTDIR MOUNTOPTS=$PERSISTENTOPTS \
/etc/init.d/mount-persistent start

echo "Mounting overlay directory to $CHROOTDIR..."
MOUNTDIR=$CHROOTDIR PERSISTENTDIR=$PERSISTENTDIR MOUNTOPTS=$OVERLAYOPTS \
/etc/init.d/mount-overlay start

for init in /sbin/init /etc/init /bin/init /bin/sh; do
	[ -e $CHROOTDIR/$init ] && break
done

install -d $CHROOTDIR
echo "Installing chroot to $CHROOTDIR..."
for dir in /dev /dev/pts /sys /proc; do
	mount -o bind $dir $CHROOTDIR$dir
done

echo "Chrooting to $chrootdir..."
chroot=$CHROOTDIR exec chroot $CHROOTDIR $init $initargs

echo "Oops... ${0##*/} is about to exit!" >&2
exit 1
