#!/bin/sh -e

IFACE=${2:-eth0}
ETHMAC=$(echo "$3" | grep -E '^[a-fA-F0-9]{2,2}:[a-fA-F0-9]{2,2}:[a-fA-F0-9]{2,2}:[a-fA-F0-9]{2,2}:[a-fA-F0-9]{2,2}:[a-fA-F0-9]{2,2}$' || true)
IP=$(echo "$4" | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' || true)
BROADCAST=$(echo "$5" | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' || true)
SUBNET=$6
PIDDIR=${PIDDIR:-/tmp/run}
PIDFILE=$PIDDIR/${0##*/}-$IFACE.pid
SCRIPT=/usr/share/${0##*/}.action
ARGS="-s -i $IFACE -f -r $SCRIPT"

case "$1" in
start)
	if ! ip -o link show up | grep -q $IFACE; then
		[ -n "$ETHMAC" ] && ip link set addr $ETHMAC dev $IFACE
		ip link set dev $IFACE up
	fi

	if [ -n "$IP" ]; then
		interface=$IFACE ip=$IP broadcast=$BROADCAST subnet=$SUBNET /usr/share/udhcpc.action bound
	else
		/etc/init.d/ifplugd start $IFACE
	fi
	;;
stop)
	/etc/init.d/ifplugd stop $IFACE
	ip link set dev $IFACE down
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Error: ${0##*/} start|stop|restart [IFACE] [ETHMAC] [IP] [BROADCAST] [SUBNET]" >&2
	exit 1
	;;
esac
