#!/bin/sh -e

IFACE=${IFACE:-$2}
IFACE=${IFACE:-eth0}
ETHMAC=$(echo "${ETHMAC:-$3}" | sed -n 's/^[a-fA-F0-9]\{2,2\}[:-][a-fA-F0-9]\{2,2\}[:-][a-fA-F0-9]\{2,2\}[:-][a-fA-F0-9]\{2,2\}[:-][a-fA-F0-9]\{2,2\}[:-][a-fA-F0-9]\{2,2\}$/&/p')
IP=$(echo "${IP:-4}" | sed -n 's/^[a-fA-F0-9]\{1,3\}\.[a-fA-F0-9]\{1,3\}\.[a-fA-F0-9]\{1,3\}\.[a-fA-F0-9]\{1,3\}$/&/p')
BROADCAST=$(echo "${BROADCAST:-5}" | sed -n 's/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$/&/p')
SUBNET=${SUBNET:-6}
NAME="interface $IFACE"
DESC="Networking interface setup"

case "$1" in
start)
	shift
	echo -n "starting $DESC: $NAME... "
	if ! ip -o link show up | grep -q $IFACE; then
		ethmac=$(echo $ETHMAC | sed -e 's,-,:,g')
		[ -n "$ethmac" ] && ip link set addr $ethmac dev $IFACE
		ip link set dev $IFACE up
		unset ethmac
	fi

	if [ -n "$IP" ]; then
		echo -n "(static ip=$IP${BROADCAST:+ broadcast=$BROADCAST}${SUBNET:+ subnet=$SUBNET}) "
		if interface=$IFACE ip=$IP broadcast=$BROADCAST subnet=$SUBNET /usr/share/udhcpc.action bound >/dev/null 2>&1; then
			echo "done."
			exit 0
		else
			echo "failed."
			exit 1
		fi
	fi

	echo -n "(dynamic) "
	if /etc/init.d/ifplugd status $IFACE >/dev/null 2>&1; then
		echo "already started."
		exit 0
	fi

	if ! /etc/init.d/ifplugd start $IFACE >/dev/null 2>&1; then
		echo "failed."
		exit 1
	fi
	echo "done."
	;;
stop)
	shift
	echo -n "stopping $DESC: $NAME... "
	if ! ip -o link show up | grep -q $IFACE; then
		echo "already stopped."
		exit 0
	fi

	if [ -z "$IP" ]; then
		if ! /etc/init.d/ifplugd status $IFACE >/dev/null 2>&1; then
			echo "already stopped."
			exit 0
		fi

		if ! /etc/init.d/ifplugd stop $IFACE >/dev/null 2>&1; then
			echo "failed."
			exit 1
		fi
	fi

	ip link set dev $IFACE down
	echo "done."
	;;
restart|reload)
	shift
	echo -n "restarting $DESC: $NAME... "
	$0 stop >/dev/null
	$0 start >/dev/null
	echo "done."
	;;
status|wait)
	/etc/init.d/ifplugd $1 $IFACE
	;;
*)
	echo "Usage: ${0##*/} {start|stop|restart|reload|status|wait} [IFACE=eth0] [ETHMAC] [IP] [BROADCAST] [SUBNET]" >&2
	exit 1
	;;
esac
