#!/bin/sh -e

mountdir=${MOUNTDIR:-/media/root-overlay}
persistentdir=${PERSISTENTDIR:-/media/persistent}
lowerdir=/
upperdir=$persistentdir/root
workdir=$persistentdir/.work

echo "Installing overlay..."
for d in $upperdir $workdir; do
	[ -d $d ] || mkdir -p $d 
done

echo "Mounting overlay directory to $mountdir..."
echo mount -olowerdir=$lowerdir,upperdir=$upperdir,workdir=$workdir -t overlay overlay $mountdir $MOUNTOPTS
mount -olowerdir=$lowerdir,upperdir=$upperdir,workdir=$workdir -t overlay overlay $mountdir $MOUNTOPTS
